NUMPY continueees....

In [2]:
import numpy as np

In [3]:
print(np.eye(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [5]:
print(np.eye(4,dtype=int))

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [6]:
print(np.eye(4,dtype=bool))

[[ True False False False]
 [False  True False False]
 [False False  True False]
 [False False False  True]]


In [7]:
print(np.logical_not(np.eye(4,dtype=int)))

[[False  True  True  True]
 [ True False  True  True]
 [ True  True False  True]
 [ True  True  True False]]


In [8]:
print(np.eye(4,3,dtype=int))

[[1 0 0]
 [0 1 0]
 [0 0 1]
 [0 0 0]]


In [12]:
np.eye(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [14]:
np.eye(5,M=4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0]])

In [17]:
np.eye(5,M=4,k=1,dtype=int)

array([[0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [18]:
# another method to create identity matrix
# identity()

In [19]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
np.identity(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [22]:
np.identity(4,dtype=bool)

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [23]:
# create 1D array and convert into 2D
# ?use methods like
# resize---permanent  and reshape--- temporary method

In [24]:
a=np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [27]:
a.ndim

1

In [29]:
a.shape

(24,)

In [30]:
a.size

24

In [37]:
    #np.resize() returns a new resized array,
# whereas a.resize() modifies the existing array in-place.


np.resize(a,(6,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [41]:
np.resize(a,(6,6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [35]:
a.resize(6,4)

In [36]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [42]:
a.resize(6,6)

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

In [38]:
a.ndim

2

In [39]:
a.shape

(6, 4)

In [40]:
a.size

24

In [43]:
# reshape use for temp. conversion


In [44]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [45]:
a.shape

(6, 4)

In [46]:
a.reshape(24)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [47]:
a.reshape(26)

ValueError: cannot reshape array of size 24 into shape (26,)

In [49]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [50]:
a.reshape(3,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [51]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [53]:
np.reshape(a,(3,8))

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [55]:
np.reshape(a,(3,9))

ValueError: cannot reshape array of size 24 into shape (3,9)

In [56]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [60]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [61]:
a.shape

(6, 4)

In [62]:
# row to column or vice versa

In [63]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [65]:
a.transpose()    #temp

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

In [66]:
a.T

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

In [69]:
x=np.arange(24)
x.reshape((6,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [70]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [72]:
x=np.arange(24).reshape((6,4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [73]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [74]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [75]:
a.size()

TypeError: 'int' object is not callable

In [76]:
a.size

24

In [77]:
a.transpose

<function ndarray.transpose>

In [78]:
a.transpose()

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

In [82]:
# Add a number in 1D array

a=np.array([10,20,30,40,50])

result =np.append(a,60)
print(result)

[10 20 30 40 50 60]


In [86]:
b=np.append(a,[70,80])
b


array([10, 20, 30, 40, 50, 70, 80])

In [87]:
a

array([10, 20, 30, 40, 50])

In [89]:
np.concatenate((a,[50,60]))

array([10, 20, 30, 40, 50, 50, 60])

In [6]:
# Add a row in 2D array
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [91]:
a.ndim

2

In [92]:
a.shape

(2, 3)

In [93]:
b=np.append(a,[[7,8,9]],axis=0)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [95]:
np.insert(a,2,[7,8,9],axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
# Add a column in 2D array

In [9]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
a = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

In [12]:
np.append(a,[[7],[8],[9]],axis=1)

array([[1, 2, 7],
       [3, 4, 8],
       [5, 6, 9]])

In [13]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
np.insert(a,2,[7,8,9],axis=1)

array([[1, 2, 7],
       [3, 4, 8],
       [5, 6, 9]])

In [ ]:
# Remove a number from 1D array

In [15]:
a=np.array([10,20,30,40,50,60])
a

array([10, 20, 30, 40, 50, 60])

In [17]:
np.delete(a,2)

array([10, 20, 40, 50, 60])

In [ ]:
# Remove a row from 2D array

In [18]:
a=np.full((4,3),10)
a

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [20]:
a=np.random.randint(1,20,(3,4))
a

array([[ 1,  3,  5,  7],
       [ 4, 15,  3, 15],
       [ 7,  4,  4,  5]])

In [21]:
np.delete(a,2,axis=0)

array([[ 1,  3,  5,  7],
       [ 4, 15,  3, 15]])

In [22]:
a

array([[ 1,  3,  5,  7],
       [ 4, 15,  3, 15],
       [ 7,  4,  4,  5]])

In [ ]:
# Remove a column from 2D array

In [23]:
np.delete(a,3,axis=1)

array([[ 1,  3,  5],
       [ 4, 15,  3],
       [ 7,  4,  4]])

In [ ]:
# Concatenate 2 arrays

In [24]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [26]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6])

In [27]:
a=np.array([
    [1,2],
    [3,4],
])

b=np.array([[5,6],[7,8]])

In [28]:
a,b

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [29]:
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [30]:
np.concatenate((a,b),axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])