# NumPy

In [2]:
import numpy as np

In [3]:
np.__version__

'2.1.3'

In [4]:
a = np.array([10,20,30,40])
a

array([10, 20, 30, 40])

In [5]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [6]:
np.array([1,2,3,4.])

array([1., 2., 3., 4.])

In [7]:
np.array([1,2,3,4,2+3j])

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 2.+3.j])

In [8]:
np.array([1,2,3,4,'a'])

array(['1', '2', '3', '4', 'a'], dtype='<U21')

In [9]:
# different ways to create numpy array

np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [12]:
# use zeros to create array of zeros


In [13]:
np.zeros(5)  #1D array

array([0., 0., 0., 0., 0.])

In [14]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [19]:
np.zeros(5,dtype=complex)

array([0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j])

In [20]:
np.zeros(5,dtype=bool)

array([False, False, False, False, False])

In [21]:
np.zeros(5,dtype=str)

array(['', '', '', '', ''], dtype='<U1')

In [15]:
# use ones to create array of 1's

np.ones(5)

array([1., 1., 1., 1., 1.])

In [22]:
np.ones(5,dtype=bool)

array([ True,  True,  True,  True,  True])

In [24]:
b = np.ones(5,dtype=str)
b.ndim

1

In [28]:
# 2D array

c =np.zeros((2,3))
c

array([[0., 0., 0.],
       [0., 0., 0.]])

In [29]:
c.ndim

2

In [30]:
c=np.zeros([3,4])
c

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [33]:
# 3D array

c= np.zeros((4,2,3))
c

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [34]:
# create 2D and 3D arrays of 1's


In [41]:
a=np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [42]:
a.ndim

1

In [43]:
a=np.ones((3,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [44]:
a.ndim

2

In [46]:
a=np.ones((4,3,5))
a

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [47]:
a.ndim

3

In [48]:
# full

a=np.full((3,3),-1)
a

array([[-1, -1, -1],
       [-1, -1, -1],
       [-1, -1, -1]])

In [49]:
a=np.full((2,3,3),-1)
a

array([[[-1, -1, -1],
        [-1, -1, -1],
        [-1, -1, -1]],

       [[-1, -1, -1],
        [-1, -1, -1],
        [-1, -1, -1]]])

In [ ]:
zeros(np.arange(5,8))

In [50]:
np.arange(5,8)

array([5, 6, 7])

In [56]:
np.zeros(np.arange(5,8))


array([[[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
    

In [ ]:
# q1. create a 4*4 array of all false value


In [63]:
a=np.zeros((4,4),dtype=bool)
a

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [68]:
a=np.full((4,4),False)
a

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
# q2. create a 4*4 array of all true value

In [65]:
a=np.ones((4,4),dtype=bool)
a

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [70]:
a=np.full((4,4),True)
a

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
# q3. create a 4*4 array of diagonal 1 and non diag 0

In [72]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [71]:
a=np.eye(4,dtype=int)
a

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [ ]:
# q4. create a 4*4 array of diagonal True and non diag False

In [73]:
a=np.eye(4,dtype=bool)
a

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [ ]:
# q5. create a 4*4 array of diagonal False and non diag True

In [77]:
a=(np.eye(4,dtype=bool))
a


array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [78]:
a=np.logical_not(np.eye(4,dtype=bool))
a


array([[False,  True,  True,  True],
       [ True, False,  True,  True],
       [ True,  True, False,  True],
       [ True,  True,  True, False]])

In [79]:
a=~(np.eye(4,dtype=bool))
a


array([[False,  True,  True,  True],
       [ True, False,  True,  True],
       [ True,  True, False,  True],
       [ True,  True,  True, False]])